# Generated by Django 5.0.1 on 2024-01-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divelog',
            name='depth',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='divingtime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='partner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='pickTanks',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='suit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='temperature',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='visibility',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='weight',
            field=models.CharField(max_length=255),
        ),
    ]
