# Generated by Django 5.0.1 on 2024-01-16 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divelog', '0006_alter_divelog_divespot'),
    ]

    operations = [
        migrations.AddField(
            model_name='divelog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
