# Generated by Django 5.0.1 on 2024-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='divespot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotname', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
